- name: Deploy TechSync Container
  hosts: servers
  become: true

  tasks:

    - name: Install Docker
      dnf:
        name: docker
        state: present

    - name: Start Docker
      service:
        name: docker
        state: started
        enabled: true

    - name: Add ec2-user to docker group
      user:
        name: ec2-user
        groups: docker
        append: yes

    - name: Pull latest Docker image
      command: docker pull harsha2318/techsync:latest

    # Fix: Remove ANY existing containers using this image
    - name: Remove old containers (avoid port conflicts)
      shell: docker ps -a --filter "ancestor=harsha2318/techsync:latest" -q | xargs -r docker rm -f

    # ensure named container is removed
    - name: Stop existing container (safe)
      shell: docker stop techsync || true

    - name: Remove existing container (safe)
      shell: docker rm techsync || true

    - name: Ensure host data directory exists
      file:
        path: /home/ec2-user/data
        state: directory
        owner: ec2-user
        group: ec2-user
        mode: '0755'

    - name: Run new container
      command: >
        docker run -d
        --name techsync
        -p 8080:8080
        -v /home/ec2-user/data:/data
        --restart unless-stopped
        harsha2318/techsync:latest

    - name: Install Nginx
      dnf:
        name: nginx
        state: present

    - name: Configure Nginx reverse proxy
      copy:
        dest: /etc/nginx/nginx.conf
        content: |
          events {}
          http {
              server {
                  listen 80;
                  server_name _;

                  location / {
                      proxy_pass http://localhost:8080;
                      proxy_set_header Host $host;
                      proxy_set_header X-Real-IP $remote_addr;
                  }
              }
          }

    - name: Start Nginx
      service:
        name: nginx
        state: started
        enabled: true

    - name: Restart Nginx
      service:
        name: nginx
        state: restarted

    - name: Verify app health
      command: curl http://localhost:8080/api/health
      register: health_output

    - name: Show health output
      debug:
        var: health_output.stdout